### PR TITLE
add option to overwrite gardenlet image vector

### LINKED ISSUE #241: Make image overwrites configurable
**What would you like to be added**:

Gardener offers the possibility to define image overwrites in the gardener apiserver and the gardenlet (see gardener docs https://github.com/gardener/gardener/blob/master/docs/deployment/image_vector.md).
It should be possible to define in the acre.yaml these overwrites.
I guess they have to be added herer https://github.com/gardener/garden-setup/blob/master/components/gardener/runtime/deployment.yaml#L86

### PR DESCRIPTION
**Pull request by Diaphteiros**
**Which issue(s) this PR fixes**:
Fixes #241 

**Release note**:

```improvement operator
It's now possible to overwrite the gardenlet's image vector. Please see the [docs](docs/extended/iaas.md#image-vector-overwrite) for further information.
```

### CODE REVIEW

**Comment by Diaphteiros** [comment]
@dergeberl @einfachnuralex I added the option to specify image vector overwrites in the acre.yaml (see the updated docs/extended/iaas.md file for documentation), but I don't have a fitting image vector at hand to test whether everything works. Maybe you could have a look at the changes and test whether this solves the issue?

**Comment by dergeberl** [comment]
@Diaphteiros the function seems work fine. Tag and Version are set to a required field but works without setting it. I found the following part in the gardener code https://github.com/gardener/gardener/blob/master/pkg/utils/imagevector/imagevector.go#L73-L96

**Comment by Diaphteiros** [comment]
@dergeberl Thanks for testing! I didn't know those fields were optional, I can remove the hard validation for them.

**Comment by Diaphteiros** [comment]
OK, I changed it so the `tag` and `version` fields are not required anymore. Will merge the PR now.

**Pull request merged**
