### PR TITLE
add valuesOverwrite for image in gvisor

### PR DESCRIPTION
**Pull request by dergeberl**
**What this PR does / why we need it**:

Add availability to overwrite settings for imageVectorOverwrite in gvisor.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```feature operator
NONE
```

### CODE REVIEW

**Comment by Diaphteiros** [comment]
The image should already be configurable via `landscape.versions.gardener.extensions.runtime-gvisor` (and then `image_tag` and/or `image_repo`). In addition to that, this line https://github.com/gardener/garden-setup/blob/master/components/gardener/extensions/deployment.yaml#L471 does allow a generic overwrite of the values file for the extension helm chart. To overwrite, add `valueOverwrites` (not `valuesOverwrite`) to the aforementioned path in the acre.yaml and specify your new values there.

So, I think that the line you added is actually not needed. Please have a look at my comments and if you agree, close the PR. If you don't agree, please explain which case you are trying to solve that is not covered by the existing mechanisms.

**Comment by dergeberl** [comment]
I can`t inject settings for `imageVectorOverwrite` in my case:
Example:
```
runtime-gvisor:
  valueOverwrites:
    test: test 
    image:
      imageVectorOverwrite: |
        images:
        - name: runtime-gvisor-installation
          sourceRepository: github.com/gardener/gardener-extension-runtime-gvisor
          repository: eu.gcr.io/gardener-project/gardener/extensions/runtime-gvisor-installation
```

Without the the change in this PR only the `test: test` is injected but `image.imageVectorOverwrite` is ignored. I think this is because I did not overwrite `repository`and `tag`.

**Comment by Diaphteiros** [comment]
Hm, yeah, the way spiff templating works, it could indeed be that you can't add any new fields to the `image` node. But is that needed? Instead of injecting the imageVectorOverwrite, just put the `repository` part of it under `landscape.versions.gardener.extensions.runtime-gvisor.image_repo` and optionally adapt `image_tag` as well.

So, the functionality that you want is there, it just uses a different syntax than what you would like to use. If you think your syntax has advantages, we can add the line which you proposed, but then I'd prefer that we add it to all extensions, so they all behave the same way. WDYT?

**Comment by dergeberl** [comment]
Hmm, I am not sure. In my opinion it should be possible to use the `valueOverwrites` like it is documented (https://github.com/gardener/garden-setup/blob/master/docs/extended/gardener.md#valueoverwrites-for-extensions) to overwrite values. Maybe it is better to add the possibility to all extensions, like in this PR. But I guess it is a point for all settings, for example `resources` https://github.com/gardener/garden-setup/blob/master/components/gardener/extensions/deployment.yaml#L476 . What do you think?

**Comment by Diaphteiros** [comment]
@dergeberl Sorry, I forgot to follow up on this. The problem with "deep merges" is that they are not supported by the templating language and therefore we would need lots of merge annotations in the templates, which is annoying and hard to read. I'll try to find out whether we can support this kind of merge, then this would be a lot easier and cleaner.

**Comment by dergeberl** [comment]
This is quite old and also not relevant for us anymore.

**Pull request closed without merging**
